sudo: false
language: cpp
compiler:
    - gcc
    - clang
#before_script:
#    - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
#    - sudo apt-get update -qq
#    - sudo apt-get install libboost-all-dev
#    - sudo apt-get --only-upgrade install cmake
script: mkdir build && cd build && cmake .. && make
#notifications:
#    email:
#        recipients:
#            - kph1958@rit.edu
#        on_success: change
#        on_failure: always
#
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
            - gcc-4.8
            - g++-4.8
            - clang
            - cmake
            - cmake-data
            - libboost1.55-all-dev
