sudo: required
language: cpp
compiler:
    - gcc
    - clang

env:
    global:
        # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
        - secure: "gFKFbcH0b7+2uOSig/50kw0XapG0B9Nff/twYtDQP2EKr4+23Nl9WadFw4NlzIzKlVSlwYzC9CQQHg65iewOQqHdYxucES4AEhGtcgl+VdobDK02j4NR35wKXGcuLBjCfnwLiF6xnwcHxR4Oa6RyeNYiFexrPPWfJXdEWIV7j2udv0NLnuJNnGznqzK3E5Mqv/PaBDRUUjH0NPQPPmv9kcqaF34Ud5B/Bw/MdblwLv+u8b/j1VhSwJ8WB8gNR9Hh3QALVQsaywZT5zaoGWmXNCO0wKbhRmCCYg0ZEsDGJQVqV6Tn3x+3Z2rOukBAf1jWkFB9YQ6fGUtGR4c5GScdVRwPsL8QK2cAB+c2OMRBN3EC3cZo3o6knDyOvhqb7xP7nGeiP0YoC0SiIWl8yiRgHF5scGrdxT2RoshRG6JTZGZ9tqLaj98HgRpyUMpk/YDDqf7jH28dJYgjO60pv0FPdPof4D26RDbUNZqwo/1QBRoAEW6+vNRWTS1YAQpKCBhhZSaD+wFrlvWd5R3N4o15IyI3lfxU9DhGUO+9gYgEGtZ3wE1uJfUxT+Z9MZWE2OJmZ4LKbHvdFrnuEUT0DRt8veKiEXqaEH7AZlnatqbnVF6m5f+j8EdHxejBgYR4aBewZLMnGx6B/a8qJ4qZ8MuH/cwpW/1Iap4ykxcV9OhsRHk="

script:
    - cmake
    - make
    - make test


before_install:
    - pip install --user cpp-coveralls
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

addons:
    coverity_scan:
        project:
            name: "khanny17/Quadcopter"
            description: "<Your project description here>"
            notification_email: khanny17@gmail.com
            build_command_prepend: "cmake"
            build_command:   "make"
            branch_pattern: coverity_scan
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
            - gcc-4.8
            - g++-4.8
            - clang
            - cmake
            - cmake-data
            - libboost1.55-all-dev

#notifications:
#    email:
#        recipients:
#            - kph1958@rit.edu
#        on_success: change
#        on_failure: always

